# Elasticsearch/OpenSearch service for search functionality
{{ $search := .Config.Stack.Services.Search }}
{{ $searchVersion := .Config.Stack.SearchVersion }}

{{ if or (eq $search "elasticsearch") (eq $search "opensearch") }}
services:
  elasticsearch:
    hostname: {{ .Config.ProjectName }}-elasticsearch
    image: {{ if eq $search "elasticsearch" }}{{ $.ImageRepository }}elasticsearch:{{ $searchVersion }}{{ else }}{{ $.ImageRepository }}opensearch:{{ $searchVersion }}{{ end }}

    environment:
      - discovery.type=single-node
      {{ if eq $search "elasticsearch" }}
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
      - "indices.query.bool.max_clause_count=10240"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      {{ else }}
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.routing.allocation.disk.threshold_enabled=false
      - "indices.query.bool.max_clause_count=10240"
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
      {{ end }}
    networks:
      govard-net:
        aliases:
          - opensearch
      govard-proxy: {}
    volumes:
      - search-data{{ if .Config.Profile }}-{{ .Config.Profile }}{{ end }}:{{ if eq $search "elasticsearch" }}/usr/share/elasticsearch/data{{ else }}/usr/share/opensearch/data{{ end }}

volumes:
  search-data{{ if .Config.Profile }}-{{ .Config.Profile }}{{ end }}:
{{ end }}
