{{ if .Config.Stack.Features.LiveReload }}
services:
  watcher:
    image: node:{{ .Config.Stack.NodeVersion }}-alpine
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - govard-net
    command: ["sh", "-c", "npm install && npx grunt watch || npx vite --host 0.0.0.0"]
    environment:
      NODE_ENV: development
{{ end }}
