{{ $queue := .Config.Stack.Services.Queue }}
{{ $queueVersion := .Config.Stack.QueueVersion }}
{{ if eq $queue "rabbitmq" }}
services:
  rabbitmq:
    hostname: {{ .Config.ProjectName }}-rabbitmq
    image: {{ $.ImageRepository }}rabbitmq:{{ $queueVersion }}
    networks:
      - govard-net
{{ end }}
