# Varnish service for full-page caching

services:
  {{ if .Config.Stack.Features.Varnish }}
  varnish:
    hostname: {{ .Config.ProjectName }}-varnish
    image: {{ $.ImageRepository }}varnish:{{ .Config.Stack.VarnishVersion }}
    volumes:
      - '{{ .VarnishVclPath }}:/etc/varnish/default.vcl:ro'
    command: "-p http_resp_hdr_len=1m -p http_resp_size=10M -p workspace_backend=64m -p workspace_client=64m -p gzip_buffer=1m -p vsl_buffer=1m -p fetch_chunksize=256k -p thread_pools=4 -p thread_pool_max=2000 -p http_gzip_support=off"
    networks:
      - govard-net
      - govard-proxy
    depends_on:
      - web
  {{ end }}
