package engine

import "strings"

// FrameworkConfig defines the configuration for a specific framework
type FrameworkConfig struct {
	Name              string
	NGINXPUBLIC       string
	NGINXTemplate     string
	DatabaseName      string
	DefaultPHP        string
	DefaultNodeVer    string
	DefaultDB         string
	DefaultDBVer      string
	DefaultMySQLVer   string
	DefaultNginxVer   string
	DefaultApacheVer  string
	DefaultCacheVer   string
	DefaultSearchVer  string
	DefaultVarnishVer string
	DefaultQueueVer   string
	DefaultWebServer  string
	DefaultSearch     string
	DefaultCache      string
	DefaultQueue      string
	Includes          []string // List of include files to load
}

// FrameworkConfigs maps framework names to their configurations
var FrameworkConfigs = map[string]FrameworkConfig{
	"magento2": {
		Name:              "magento2",
		NGINXPUBLIC:       "/pub",
		NGINXTemplate:     "magento2.conf",
		DatabaseName:      "magento",
		DefaultPHP:        "8.4",
		DefaultNodeVer:    "24",
		DefaultDB:         "mariadb",
		DefaultDBVer:      "11.4",
		DefaultMySQLVer:   "8.4",
		DefaultNginxVer:   "1.28",
		DefaultApacheVer:  "2.4",
		DefaultCacheVer:   "7.4",
		DefaultSearchVer:  "2.19",
		DefaultVarnishVer: "7.6",
		DefaultQueueVer:   "3.13.7",
		DefaultWebServer:  "nginx",
		DefaultSearch:     "opensearch",
		DefaultCache:      "redis",

		DefaultQueue: "none",
		Includes: []string{
			"includes/base.yml",
			"includes/redis.yml",
			"includes/elasticsearch.yml",
			"includes/varnish.yml",
			"includes/rabbitmq.yml",
			"includes/selenium.yml",
			"includes/livereload.yml",
		},
	},
	"laravel": {
		Name:              "laravel",
		NGINXPUBLIC:       "/public",
		NGINXTemplate:     "laravel.conf",
		DatabaseName:      "laravel",
		DefaultPHP:        "8.4",
		DefaultDB:         "mariadb",
		DefaultDBVer:      "11.4",
		DefaultMySQLVer:   "8.4",
		DefaultNginxVer:   "1.28",
		DefaultApacheVer:  "2.4",
		DefaultCacheVer:   "7.4",
		DefaultSearchVer:  "3.0",
		DefaultVarnishVer: "7.4",
		DefaultQueueVer:   "3.13.7",
		DefaultWebServer:  "nginx",
		DefaultSearch:     "none",
		DefaultCache:      "none",
		DefaultQueue:      "none",
		Includes: []string{
			"includes/base.yml",
			"includes/redis.yml",
			"includes/elasticsearch.yml",
			"laravel/services.yml",
			"includes/rabbitmq.yml",
		},
	},
	"nextjs": {
		Name:             "nextjs",
		NGINXPUBLIC:      "",
		NGINXTemplate:    "nodejs.conf",
		DatabaseName:     "",
		DefaultPHP:       "",
		DefaultNodeVer:   "24",
		DefaultDB:        "",
		DefaultDBVer:     "",
		DefaultNginxVer:  "1.28",
		DefaultApacheVer: "2.4",
		DefaultQueueVer:  "3.13.7",
		DefaultWebServer: "nginx",
		DefaultSearch:    "none",
		DefaultCache:     "none",
		DefaultQueue:     "none",
		Includes: []string{
			"nextjs/services.yml",
			"includes/redis.yml",
			"includes/rabbitmq.yml",
		},
	},
	"drupal": {
		Name:              "drupal",
		NGINXPUBLIC:       "/web",
		NGINXTemplate:     "drupal.conf",
		DatabaseName:      "drupal",
		DefaultPHP:        "8.4",
		DefaultDB:         "mariadb",
		DefaultDBVer:      "11.4",
		DefaultMySQLVer:   "8.4",
		DefaultNginxVer:   "1.28",
		DefaultApacheVer:  "2.4",
		DefaultCacheVer:   "7.4",
		DefaultSearchVer:  "3.0",
		DefaultVarnishVer: "7.4",
		DefaultQueueVer:   "3.13.7",
		DefaultWebServer:  "nginx",
		DefaultSearch:     "none",
		DefaultCache:      "none",
		DefaultQueue:      "none",
		Includes: []string{
			"includes/base.yml",
			"includes/redis.yml",
			"includes/elasticsearch.yml",
			"includes/rabbitmq.yml",
		},
	},
	"symfony": {
		Name:              "symfony",
		NGINXPUBLIC:       "/public",
		NGINXTemplate:     "symfony.conf",
		DatabaseName:      "symfony",
		DefaultPHP:        "8.4",
		DefaultDB:         "mariadb",
		DefaultDBVer:      "11.4",
		DefaultMySQLVer:   "8.4",
		DefaultNginxVer:   "1.28",
		DefaultApacheVer:  "2.4",
		DefaultCacheVer:   "7.4",
		DefaultSearchVer:  "3.0",
		DefaultVarnishVer: "7.4",
		DefaultQueueVer:   "3.13.7",
		DefaultWebServer:  "nginx",
		DefaultSearch:     "none",
		DefaultCache:      "none",
		DefaultQueue:      "none",
		Includes: []string{
			"includes/base.yml",
			"includes/redis.yml",
			"includes/elasticsearch.yml",
			"symfony/services.yml",
			"includes/rabbitmq.yml",
		},
	},
	"magento1": {
		Name:              "magento1",
		NGINXPUBLIC:       "",
		NGINXTemplate:     "magento1.conf",
		DatabaseName:      "magento",
		DefaultPHP:        "8.1",
		DefaultDB:         "mariadb",
		DefaultDBVer:      "10.11",
		DefaultMySQLVer:   "8.0",
		DefaultNginxVer:   "1.28",
		DefaultApacheVer:  "2.4",
		DefaultCacheVer:   "7.0",
		DefaultVarnishVer: "6.0",
		DefaultQueueVer:   "3.13.7",
		DefaultWebServer:  "nginx",
		DefaultSearch:     "none",
		DefaultCache:      "none",
		DefaultQueue:      "none",
		Includes: []string{
			"includes/base.yml",
			"includes/redis.yml",
			"magento1/services.yml",
			"includes/rabbitmq.yml",
		},
	},
	"openmage": {
		Name:              "openmage",
		NGINXPUBLIC:       "",
		NGINXTemplate:     "magento1.conf",
		DatabaseName:      "openmage",
		DefaultPHP:        "8.2",
		DefaultDB:         "mariadb",
		DefaultDBVer:      "10.11",
		DefaultMySQLVer:   "8.0",
		DefaultNginxVer:   "1.28",
		DefaultApacheVer:  "2.4",
		DefaultCacheVer:   "7.0",
		DefaultVarnishVer: "6.0",
		DefaultQueueVer:   "3.13.7",
		DefaultWebServer:  "nginx",
		DefaultSearch:     "none",
		DefaultCache:      "none",
		DefaultQueue:      "none",
		Includes: []string{
			"includes/base.yml",
			"includes/redis.yml",
			"magento1/services.yml",
			"includes/rabbitmq.yml",
		},
	},
	"shopware": {
		Name:              "shopware",
		NGINXPUBLIC:       "/public",
		NGINXTemplate:     "shopware.conf",
		DatabaseName:      "shopware",
		DefaultPHP:        "8.4",
		DefaultDB:         "mariadb",
		DefaultDBVer:      "11.4",
		DefaultMySQLVer:   "8.4",
		DefaultNginxVer:   "1.28",
		DefaultApacheVer:  "2.4",
		DefaultCacheVer:   "7.4",
		DefaultSearchVer:  "3.0",
		DefaultVarnishVer: "7.4",
		DefaultQueueVer:   "3.13.7",
		DefaultWebServer:  "nginx",
		DefaultSearch:     "none",
		DefaultCache:      "none",
		DefaultQueue:      "none",
		Includes: []string{
			"includes/base.yml",
			"includes/redis.yml",
			"includes/elasticsearch.yml",
			"shopware/services.yml",
			"includes/rabbitmq.yml",
		},
	},
	"cakephp": {
		Name:              "cakephp",
		NGINXPUBLIC:       "/webroot",
		NGINXTemplate:     "cakephp.conf",
		DatabaseName:      "cakephp",
		DefaultPHP:        "8.4",
		DefaultDB:         "mariadb",
		DefaultDBVer:      "11.4",
		DefaultMySQLVer:   "8.4",
		DefaultNginxVer:   "1.28",
		DefaultApacheVer:  "2.4",
		DefaultCacheVer:   "7.4",
		DefaultVarnishVer: "7.4",
		DefaultQueueVer:   "3.13.7",
		DefaultWebServer:  "nginx",
		DefaultSearch:     "none",
		DefaultCache:      "none",
		DefaultQueue:      "none",
		Includes: []string{
			"includes/base.yml",
			"includes/redis.yml",
			"includes/rabbitmq.yml",
		},
	},
	"wordpress": {
		Name:              "wordpress",
		NGINXPUBLIC:       "/wordpress",
		NGINXTemplate:     "wordpress.conf",
		DatabaseName:      "wordpress",
		DefaultPHP:        "8.3",
		DefaultDB:         "mariadb",
		DefaultDBVer:      "11.4",
		DefaultMySQLVer:   "8.4",
		DefaultNginxVer:   "1.28",
		DefaultApacheVer:  "2.4",
		DefaultCacheVer:   "7.4",
		DefaultVarnishVer: "7.4",
		DefaultQueueVer:   "3.13.7",
		DefaultWebServer:  "nginx",
		DefaultSearch:     "none",
		DefaultCache:      "none",
		DefaultQueue:      "none",
		Includes: []string{
			"includes/base.yml",
			"includes/redis.yml",
			"includes/rabbitmq.yml",
		},
	},
	"custom": {
		Name:              "custom",
		NGINXPUBLIC:       "",
		NGINXTemplate:     "default.conf",
		DatabaseName:      "app",
		DefaultPHP:        "8.4",
		DefaultDB:         "mariadb",
		DefaultDBVer:      "11.4",
		DefaultMySQLVer:   "8.4",
		DefaultNginxVer:   "1.28",
		DefaultApacheVer:  "2.4",
		DefaultCacheVer:   "7.4",
		DefaultSearchVer:  "3.0",
		DefaultVarnishVer: "7.6",
		DefaultQueueVer:   "3.13.7",
		DefaultWebServer:  "nginx",
		DefaultSearch:     "none",
		DefaultCache:      "none",
		DefaultQueue:      "none",
		Includes: []string{
			"includes/base.yml",
			"includes/redis.yml",
			"includes/elasticsearch.yml",
			"includes/varnish.yml",
			"includes/rabbitmq.yml",
			"includes/livereload.yml",
		},
	},
}

func GetFrameworkConfig(name string) (FrameworkConfig, bool) {
	name = strings.ToLower(strings.TrimSpace(name))
	if name == "magento" {
		name = "magento2"
	}
	config, ok := FrameworkConfigs[name]
	return config, ok
}
