package engine

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

func prepareMagentoRunMappingAssets(config Config) (string, string, error) {
	if !isMagentoFramework(config.Framework) || strings.TrimSpace(config.ProjectName) == "" {
		return "", "", nil
	}

	nginxPath := filepath.Join(GovardHomeDir(), "nginx", config.ProjectName, "mage-run-map.conf")
	apachePath := filepath.Join(GovardHomeDir(), "apache", config.ProjectName, "mage-run-map.conf")

	if err := os.MkdirAll(filepath.Dir(nginxPath), 0o755); err != nil {
		return "", "", err
	}
	if err := os.MkdirAll(filepath.Dir(apachePath), 0o755); err != nil {
		return "", "", err
	}

	if err := os.WriteFile(nginxPath, []byte(buildMagentoNginxRunMap(config.StoreDomains)), 0o644); err != nil {
		return "", "", err
	}
	if err := os.WriteFile(apachePath, []byte(buildMagentoApacheRunMap(config.StoreDomains)), 0o644); err != nil {
		return "", "", err
	}

	return nginxPath, apachePath, nil
}

func isMagentoFramework(framework string) bool {
	switch strings.ToLower(strings.TrimSpace(framework)) {
	case "magento1", "magento2", "openmage":
		return true
	default:
		return false
	}
}

func buildMagentoNginxRunMap(mappings StoreDomainMappings) string {
	lines := []string{
		"map $host $mage_run_code {",
		`    default "";`,
	}

	typedHosts := sortedStoreDomainHosts(mappings)
	for _, host := range typedHosts {
		mapping := mappings[host]
		if mapping.ScopeType() == "" || mapping.ScopeCode() == "" {
			continue
		}
		lines = append(lines, fmt.Sprintf("    %s %s;", host, mapping.ScopeCode()))
	}
	lines = append(lines, "}", "", "map $host $mage_run_type {", `    default "";`)
	for _, host := range typedHosts {
		mapping := mappings[host]
		if mapping.ScopeType() == "" || mapping.ScopeCode() == "" {
			continue
		}
		lines = append(lines, fmt.Sprintf("    %s %s;", host, mapping.ScopeType()))
	}
	lines = append(lines, "}", "")
	return strings.Join(lines, "\n")
}

func buildMagentoApacheRunMap(mappings StoreDomainMappings) string {
	lines := []string{"# Generated by Govard"}
	for _, host := range sortedStoreDomainHosts(mappings) {
		mapping := mappings[host]
		if mapping.ScopeType() == "" || mapping.ScopeCode() == "" {
			continue
		}
		hostPattern := "^" + regexp.QuoteMeta(host) + "(?::\\d+)?$"
		lines = append(lines,
			fmt.Sprintf(`SetEnvIfNoCase Host "%s" MAGE_RUN_CODE=%s`, hostPattern, mapping.ScopeCode()),
			fmt.Sprintf(`SetEnvIfNoCase Host "%s" MAGE_RUN_TYPE=%s`, hostPattern, mapping.ScopeType()),
		)
	}
	lines = append(lines, "")
	return strings.Join(lines, "\n")
}
